services:
  postgres-myshop-db:
    image: 'postgres:16.2-alpine'
    container_name: 'postgres-myshop-db'
    ports:
      - '5432:5432'
    volumes:
      - './.postgres-data:/var/lib/postgresql/myshop/data'
    environment:
      LC_ALL: 'C.UTF-8'
      #    задать пользователя
      POSTGRES_USER: 'admin'
      #    задать пароль
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'myshop'
      PGDATA: '/var/lib/postgresql/data'
    restart: unless-stopped